spring:
  profiles:
    active: local
---      
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop          
  h2:
    console:
      enabled: true
  mandatory-file-encoding: utf-8
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

handlebars:
  enabled: true
  suffix: .html
  cache: false
  charset: utf-8

